tango_with_django_project/rango/urls.py
from django.urls import path, include
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('category/<slug:category_name_slug>/add_product/', views.AddProductView.as_view(), name='add_product'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('search/', views.search, name='search'),
    path('product/<slug>/', views.ShowProductView.as_view(), name='show_computer'),
    path('product/<slug>/review/', views.AddReviewView.as_view(), name='review'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('register/', views.register, name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add_article/', views.add_article, name="add_article"),
    path('article/', views.article_show, name="article_show"),
    path('edit_article/<str:pk>/', views.edit_article, name="edit_article"),
    path('delete_article/<str:pk>/', views.delete_article, name="delete_article"),
    path('store/', views.store_show, name="store_show"),
    path('wishlist_view/', views.wishlist_view, name="wishlist_view"),
    path('add_wishlist/<int:id>', views.add_wishlist_view, name="add_wishlist_view"),
    # path('add_wishlist/', views.add_wishlist, name="add_wishlist"),
    path('article_view/', views.article_view, name="article_view"),
    path('article_information/<str:pk>/', views.article_information, name="article_information"),
    path('store_information/<str:pk>/', views.store_information, name="store_information"),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

from rango import views


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
                  path('', views.IndexView.as_view(), name='index'),
                  path('any/', include('rango.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('registration.backends.simple.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('accounts/register', MyRegistrationView.as_view(), name='registration_register')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from rango.models import Category, UserProfile, Product, Review, Article, Store


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.MAX_LEN_NAME,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class ProductForm(forms.ModelForm):
    MAX_LEN_URL = 200
    name = forms.CharField(max_length=Product.MAX_LEN_TITLE,
                           help_text="Please enter the Product name.")
    price = forms.FloatField(help_text="Please enter Product price",
                             validators=[MinValueValidator(0)]
                             )
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    description = forms.CharField(widget=forms.Textarea, help_text="Enter Product description",
                                  max_length=Product.MAX_LEN_DESC)
    picture = forms.ImageField(help_text="Submit a picture of the product", required=False)


    class Meta:
        model = Product
        exclude = ('category', 'slug')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)


class ReviewForm(forms.ModelForm):
    rating = forms.IntegerField(validators=[MinValueValidator(0),
                                            MaxValueValidator(10)], help_text="Enter Rating out of 10")
    content = forms.CharField(widget=forms.Textarea, help_text="Enter Product description",
                              max_length=Review.MAX_LEN_CONTENT)

    class Meta:
        model = Review
        exclude = ('user', 'product', 'date')


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'picture',)


class StoreForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Name', 'style': 'width: 300px;', 'class': 'form-control'}))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Email', 'style': 'width: 300px;', 'class': 'form-control'}))

    class Meta:
        model = Store
        fields = ('name', 'email', 'slug', 'ratings',)

tango_with_django_project/rango/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib import messages
from datetime import datetime

from rango.models import Category, Product, UserProfile, Article, Store, Wishlist
from rango.forms import CategoryForm, ProductForm, UserForm, UserProfileForm, ReviewForm, UserProfileEditForm, \
    ArticleForm, StoreForm

from django.contrib import messages


class IndexView(View):
    def get(self, request):
        category_list = Category.objects.order_by('-name')[:5]
        product_list = Product.objects.order_by('-name')[:5]

        context_dict = {}

        context_dict['categories'] = category_list
        context_dict['products'] = product_list



        response = render(request, 'rango/index.html', context=context_dict)
        return response


class AboutView(View):
    def get(self, request):
        context_dict = {}


        return render(request, 'rango/about.html', context=context_dict)


def search(request):
    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            result_list_prov = Product.objects.all()

            for item in result_list_prov:

                if str(query).lower() in str(item).lower():
                    result_list.append(item)
                    print(item)
    print(result_list)

    return render(request, 'rango/search.html', {
        'result_list': result_list,
        'query': query
    })


class ShowCategoryView(View):
    def create_context_dict(self, category_name_slug):
        context_dict = {}
        try:
            category = Category.objects.get(slug=category_name_slug)
            products = Product.objects.filter(category=category).order_by('-name')

            context_dict['products'] = products
            context_dict['category'] = category
        except Category.DoesNotExist:
            context_dict['products'] = None
            context_dict['category'] = None

        return context_dict

    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'rango/category.html', context_dict)

    @method_decorator(login_required(login_url='/any/register/'))
    def post(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST['query'].strip()

        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query

        return render(request, 'rango/category.html', context_dict)


class AddCategoryView(View):
    @method_decorator(login_required(login_url='/any/register/'))
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})

    @method_decorator(login_required(login_url='/any/register/'))
    def post(self, request):
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        return render(request, 'rango/add_category.html', {'form': form})


class ShowProductView(View):
    def get(self, request, slug):
        context_dict = {}

        try:
            product = Product.objects.get(slug=slug)

            context_dict['product'] = product

        except Product.DoesNotExist:
            context_dict['product'] = product

        #passes image path to read from static files
        context_dict['pathimg'] = "images/" + str(product.slug) + ".jpg"
        print("images/" + str(product.slug) + ".jpg")
        return render(request, 'rango/product.html', context=context_dict)


class AddProductView(View):
    def get_category_name(self, category_name_slug):
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None

        return category

    @method_decorator(login_required(login_url='/any/register/'))
    def get(self, request, category_name_slug):
        form = ProductForm()
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_product.html', context_dict)

    @method_decorator(login_required(login_url='/any/register/'))
    def post(self, request, category_name_slug):
        form = ProductForm(request.POST)
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        if form.is_valid():
            if category:
                product = form.save(commit=False)
                product.category = category
                product.views = 0

                if 'picture' in request.FILES:
                    product.picture = request.FILES['picture']
                product.save()
                print(product)

                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                    category_name_slug}))
        else:
            print(form.errors)

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_product.html', context=context_dict)


class ProfileView(View):
    @method_decorator(login_required(login_url='/any/register/'))
    def get(self, request):
        context_dict = {}
        try:
            profile = UserProfile.objects.get(user__username=request.user.username)

        except UserProfile.DoesNotExist:
            return render(request, 'rango/profile-with-OAuth.html')

        return render(request, 'rango/profile.html', {'profile': profile})

    @method_decorator(login_required(login_url='/any/register/'))
    def post(self, request):
        form = UserProfileEditForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save(commit=True)
        else:
            print(form.errors)

        return render(request, 'rango/profile.html', context={'form': form})





@login_required(login_url='/any/register/')
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
                  'rango/register.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')


class AddReviewView(View):

    @method_decorator(login_required(login_url='/any/register/'))
    def get(self, request, slug):
        form = ReviewForm()
        product = Product.objects.get(slug=slug)

        if product is None:
            return redirect(reverse('rango:index'))

        context_dict = {'form': form, 'product': product}
        return render(request, 'rango/review.html', context=context_dict)

    def post(self, request, slug):
        form = ReviewForm(request.POST)
        product = Product.objects.get(slug=slug)

        if product is None:
            return redirect(reverse('rango:index'))
        if form.is_valid():
            if product:
                review = form.save(commit=False)
                review.product = product
                review.user = request.user
                review.save()

                return ShowProductView.get(ShowProductView, request, slug)
        else:
            print(form.errors)

        context_dict = {'form': form, 'product': product}
        return render(request, 'rango/review.html', context=context_dict)




@login_required(login_url='/any/register/')
def user_logout(request):
    logout(request)

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block%}
    <h1>Add a Category</h1>
    <div>
        <form action="{% url 'rango:add_category' %}" method="post" id="category_form">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}

tango_with_django_project/templates/rango/add_product.html
{% extends "rango/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add Page{% endblock %}
{% block body_block %}

        <h1 class="jumbotron-heading">Add a Product to the {{category.name}} Category</h1>
    <br />
<br />
<br />

<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" enctype="multipart/form-data"
              action="{% url 'rango:add_product' category.slug %}">
            {% csrf_token %}
            
      
            
             <div class="row">
      <div class="col-6">
        {{ form.name|as_crispy_field}}
      </div>
      <div class="col-6">
       {{ form.price|as_crispy_field}}
      </div>
    </div>
            
            {{ form.description|as_crispy_field}}
            {{ form.picture|as_crispy_field}}
            {{form.store| as_crispy_field}}
            <br />
            <div class="p-2"></div>
            
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <button class="btn btn-danger" id="back-product-btn" name="submit">
                Back
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}

tango_with_django_project/templates/rango/article.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Article
{% endblock %}

{% block body_block%}



<div class="row h-100 justify-content-center align-items-center">
    {% include 'rango/messages.html' %}
    <div class="col-md-8">
        <h1>Articles Registered</h1>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" href="{% url 'rango:add_article' %}">Add a New Article</a>
            <table class="table table-sm-5">
                    <tr>
                        <th>Title</th>
                        <th>Content</th>
                        <th>Date</th>
                        <th>Author</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>

                    {% for article in articles %}

                        <tr>
                            <td>{{ article.title }}</td>
                            <td>{{ article.content }}</td>
                            <td>{{ article.date }}</td>
                            <td>{{ article.author }}</td>

                            <td><a class="btn btn-sm btn-info" href="{% url 'rango:edit_article' article.id %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger" href="{%  url 'rango:delete_article' article.id %}">Delete</a></td>
                        </tr>

                    {% endfor %}
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li>{% if message.tags %} {% endif %}{{ message }}</li>
                    {% endfor %}
                    </ul>
                    {% endif %}
            </table>
            <a class="btn btn-secondary" href="{% url 'rango:index' %}">Return to Home</a>
        </div>
    </div>
</div>
<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script> 
{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>ANYTHING -
        {% block title_block %}
           Choose whatever you want!
        {% endblock %}
    </title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top"><img src="{% static 'images/navbar-logo.png' %}" alt="..." /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4va py-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:article_view' %}"><i class="far fa-comment-dots"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:store_show' %}"><i class="fas fa-store"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:search' %}"><i class="fas fa-search"></i></a></li>
                <li class="nav-item" id="wishlist-icon"><a class="nav-link"  href="{% url 'rango:wishlist_view' %}"><i class="far fa-heart"></i></a></li>
            {% if user.is_authenticated %}
<!--                <li class="nav-item"><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a></li>-->
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}"><i class="fas fa-desktop"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:article_show' %}"><i class="fas fa-pencil-alt"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}"><i class="fas fa-unlock"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' %}" ><i class="far fa-user"></i></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'rango:index' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'rango:register' %}"><i class="far fa-user"></i></a></li>
<!--                <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>-->
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block masthead_block%}
{% endblock %}


<div class="container-fluid">
    <div class="row">
        <main role="main" class="col-md-12 ml-sm-auto col-lg-12 px-4" style="margin-top:8rem;">
        {% block body_block%}
        {% endblock %}
            <br><br>
            <footer>
                <button style="position: absolute; right: 0; bottom:0;" class="btn" onclick='window.scrollTo({top: 0, behavior: "smooth"});'>
                    <img src="{% static 'images/go-to-top.png' %}" alt="GO TO TOP"
                     width="40px"
                    />
                </button>
                <p>&copy; 2021 Anything project written by Hwisun, Ramon, Jose</p>
            </footer>
        </main>
    </div>
</div>

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/product-script.js' %}"></script>
{% block script_block%}
{% endblock %}
</body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/delete_article.html
{% extends 'rango/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title_block %}
    Delete an Article
{% endblock %}

{% block body_block%}

<br>
<div class="row h-100 justify-content-center align-items-center">
	<div class="col-md-6">
        <h1>Delete an Article</h1>
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'rango:delete_article' item.id  %}" method="POST">
				
				{% csrf_token %}

				<input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'rango:article_show' %}">Cancel</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block masthead_block%}
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To ANYTHING!</div>
        <div class="masthead-heading text-uppercase">Which laptop suits you best?</div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#check-item">FIND OUT</a>
    </div>
</header>
{% endblock %}


{% block body_block%}

<h1><center>Check items on ANYTHING</center></h1>

<div class="container" id="check-item">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                        <ul class="list-group">
                            {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            <strong>There are no categories present.</strong>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Hot Products!</h2>
                    <p class="card-text">
                        {% if products %}
                        <ul class="list-group">
                            {% for product in products %}
                                <li class="list-group-item"><a href="{% url 'rango:show_computer' product.slug %}">{{ product.name }}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            <strong>There are no products present.</strong>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script_block%}
<!-- Core theme JS-->
<script src="{% static 'js/menu-scripts.js' %}"></script>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block%}
<h1>Login to Rango</h1>
<form action="{% url 'rango:login' %}" method="post" id="login_form">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50">
    <br>
    Password: <input type="text" name="password" value="" size="50">
    <br>
    <input type="submit" value="submit" />
</form>
{% endblock %}

tango_with_django_project/templates/rango/review.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %}
Add a Review!
{% endblock %}

{% block body_block %}
<h1>Add a Review</h1>
<div>
	<form id="review_form" method="post" action="{% url 'rango:review' product.slug %}" enctype="multipart/form-data">
		{% csrf_token %}
		
		
		<div class="col-2">
        {{ form.rating|as_crispy_field}}
      </div>
      <div class="col-8">
        {{ form.content|as_crispy_field}}
      </div>
    
		<input type="submit" name="submit" value="Add Review" />
		<input type="submit" id="back-product-btn" value="Back" />
	</form>
</div>
{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}

tango_with_django_project/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}
 <div class="jumbotron p-4">
     <div class="container">
         <h1 class="jumbotron-heading">Search with ANYTHING</h1>
     </div>
 </div>
 <div>
     <form class="form-inline" id="user-form" method="post" action="{% url 'rango:search' %}">
         {% csrf_token %}

         <div class="form-group">
             <input class="form-control" type="text" size="50" name="query" id="query" value="{{ query }}"/>
         </div>
         <br>
         <button class="btn btn-primary" type="submit" name="submit" style="float:right;">Search</button>
     </form>
 </div>
<div>
    {% if result_list %}
     <h2>Results</h2>

     <div class="list-group">
     {% for result in result_list %}
         <div class="list-group-item">
             <h3 class="list-group-item-heading">
                 <a href="{% url 'rango:show_computer' result.slug %}">{{ result.name }}</a>
             </h3>
             <p class="list-group-item-text">
                 {{ result.summary|safe|escape }}
             </p>
         </div>
     {% endfor %}
     </div>
     {% endif %}
     </div>
{% endblock %}

{% block script_block%}
<script>
    document.body.querySelector('#mainNav').classList.add('navbar-shrink')
</script>
{% endblock %}